name: Discord pulto

# 'on' is the trigger, in this case this Action will
# be triggered using cron set at a 10 minutes interval.
on:
  schedule:
    - cron: "*/10 * * * *"

# 'jobs' are the routines, we only have
# one when the instance is built.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up Nodejs
        uses: actions/setup-python@v2
        with:
          node-version: "16.14.0"
          architecture: "x64"

      - name: Running Script
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          npm init -y
          npm install discord.js
          node .
